sudo: false
language: python
cache: pip
python:
  - "3.6"
addons:
  apt:
    packages:
    - lftp
  chrome: stable
deploy:
  skip_cleanup: true
  provider: script
  script: curl https://raw.githubusercontent.com/jpmckinney/opendataservices-deploy/exclude/open-contracting-standard-deploy.sh | bash -
  on:
    all_branches: true
install:
  - curl -O https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PATH:`pwd`/chromedriver
  - pip install -r requirements.txt
script:
  - flake8
  - make
  - py.test -rs --tb=line
