name: CI
on: [push, pull_request]
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      # Don't install editable projects in the current working directory.
      # https://pip.pypa.io/en/latest/reference/pip_install/#install-src
      - run: pip install --src $GITHUB_WORKSPACE/../src -r requirements.txt
      # Google Chrome and ChromeDriver are already included.
      # https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
      - if: github.repository == 'open-contracting/standard_profile_template'
        run: make update extract
      - run: make
      # - run: |
      #     make linkcheck
      #     rm -f output.json output.txt
      - run: pytest
      # Deploy the built documentation to the staging directory.
      - if: github.event_name == 'push'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: standard.open-contracting.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWLziEiV46d9iInFXAR/PxPvotcpmMtbwO8GkTF2/AFUkyiSd8/Yg5HXUoWBz7hbRwg2O+q5F1QfD57vevBV7c+JKyBbKVOi/mXaf7uACxer419RTgKcpaMhNRi708XWhNlWiKp3Afs/MDMvMdWSrU+Ht7biNb1OMGjfNMDdlsJxPycxMQ7Fu7i+kdyMkKLYDIHNeEw0aW9PtMTReUE0y/Ghn44PDR2u9/oZsEhC0ELDQUfsjtCcoM91FH1tjRBZkOW/j5940nMoJpbVhFHTC3YY9Mh2kV+N6Whht5nghJ7Jl2vN5W0Uer+TNMVRV4QMu8xK5HXbjKFMpaK+j4gBs9
      - if: github.event_name == 'push'
        uses: little-core-labs/netrc-creds@v2.1.0
        with:
          machine: standard.open-contracting.org
          login: manage
          password: ${{ secrets.ELASTICSEARCH_PASSWORD }}
      - if: github.event_name == 'push' && success() && github.repository != 'open-contracting/standard_profile_template'
        env:
          PATH_PREFIX: ""
          PRODUCTION: ${{ startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/latest' || github.ref == 'refs/heads/1.0' || github.ref == 'refs/heads/1.1' }}
          RELEASE: ${{ startsWith(github.ref, 'refs/tags') }}
          VERSION: "1.1"
        run: curl -sS https://raw.githubusercontent.com/open-contracting/deploy/main/deploy-docs.sh | bash -
