name: CI
on: [push, pull_request]
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: '**/requirements*.txt'
      # Don't install editable projects in the current working directory.
      # https://pip.pypa.io/en/latest/reference/pip_install/#install-src
      - run: pip install --src $GITHUB_WORKSPACE/../src -r requirements.txt
      - if: github.repository == 'open-contracting/standard_profile_template'
        run: make update extract
      - run: make
      # Disable linkcheck as it is too slow for development.
      # - run: |
      #     make linkcheck
      #     rm -f output.json output.txt
      - run: pytest -W error
      # Deploy the built documentation to the staging directory.
      - if: github.event_name == 'push'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: standard.open-contracting.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGveFGTJ9yyObNGDUCUyzyFkm6Kzh3YqIt1qB7B/KU6E
      - if: github.event_name == 'push'
        uses: bcomnes/netrc-creds@v2
        with:
          machine: standard.open-contracting.org
          login: manage
          password: ${{ secrets.ELASTICSEARCH_PASSWORD }}
      - if: github.event_name == 'push' && success() && github.repository != 'open-contracting/standard_profile_template'
        env:
          PATH_PREFIX: ""
          PRODUCTION: ${{ startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/latest' || github.ref == 'refs/heads/1.0' || github.ref == 'refs/heads/1.1' }}
          RELEASE: ${{ startsWith(github.ref, 'refs/tags') }}
          VERSION: "1.1"
        shell: bash
        run: curl -sS https://raw.githubusercontent.com/open-contracting/deploy/main/deploy-docs.sh | bash -
